### PR TITLE
feat: put self-hosted documentation in its own hierarchy

### PR DESCRIPTION
**Pull request by notdryft**
Effort to move Self-Hosted documentation out of the main documentation.

Production URL is https://docs.gatling.io/self-hosted
Local URL is http://localhost:1313/self-hosted (unless you use `--port`)

Local server with:

```console
./bin/entrypoint self-hosted-server
```

Other commands will build the Self-Hosted documentation first, and then the main tree.

Tried removing reference and having everything at the first level:

Screenshot 2024-06-13 at 12 15 43

### CODE REVIEW

**Review by slandelle — CHANGES_REQUESTED** [review]
Please put on hold. IIRC, Paul-Henri wanted to call it something like "self-hosted v1". Waiting for hime.

**Comment by stb13579** [comment]
One quick win in this format: eliminate Users and Admin. Users = Test execution. Move Admin to the same level and rename Test Administration.

**Comment by stb13579** [comment]
> Please put on hold. IIRC, Paul-Henri wanted to call it something like "self-hosted v1". Waiting for hime.

Is there a decision on the naming?

**Comment by slandelle** [comment]
Note: please don't spend too much time on this, trying to make things perfect. This is the legacy product we want to kill.
Good is better than perfect.

**Comment by slandelle** [comment]
> Please put on hold. IIRC, Paul-Henri wanted to call it something like "self-hosted v1". Waiting for hime.
> Is there a decision on the naming?

Yes. As explained to @notdryft and @guilgaly this morning: I have warned the different stakeholder that in an absence of a decision by today's morning we'll go with `self-hosted-legacy`. So here we are.

**Comment by notdryft** [comment]
> Please put on hold. IIRC, Paul-Henri wanted to call it something like "self-hosted v1". Waiting for hime.

Changed the header, the link from self-hosted to self-hosted-legacy, not renaming all the occurence of Self-Hosted to "Self-Hosted Legacy" inside the doc though. Header is still missing a link back to the main doc.

Screenshot 2024-06-18 at 16 29 08

**Comment by slandelle** [comment]
> Header is still missing a link back to the main doc.

Are you adding it as part of this PR?

**Comment by notdryft** [comment]
> > Header is still missing a link back to the main doc.
> 
> Are you adding it as part of this PR?

Think I'll do it after.

**Comment by slandelle** [comment]
@notdryft l'url doit être https://docs.gatling.io/self-hosted-legacy/

**Comment by notdryft** [comment]
> @notdryft l'url doit être https://docs.gatling.io/self-hosted-legacy/

Ca sera le cas !

Et nvm:

Screenshot 2024-06-18 at 17 10 40

**Pull request merged**
